import Layout from "components/Layout"
import "dist/main.css";
import { Metadata } from "next";

export const metadata : Metadata = {
  title: 'Idealist',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
